/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as rootIndexRouteImport } from './routes/(root)/index'
import { Route as rootTooltipRouteImport } from './routes/(root)/tooltip'
import { Route as rootToastRouteImport } from './routes/(root)/toast'
import { Route as rootPopoverRouteImport } from './routes/(root)/popover'
import { Route as rootPanelRouteImport } from './routes/(root)/panel'
import { Route as rootModalRouteImport } from './routes/(root)/modal'
import { Route as rootMenuRouteImport } from './routes/(root)/menu'
import { Route as rootAppleIntelligenceRouteImport } from './routes/(root)/apple-intelligence'
import { Route as WebviewsTrayIndexRouteImport } from './routes/webviews/tray/index'
import { Route as WebviewsPopoverIndexRouteImport } from './routes/webviews/popover/index'
import { Route as WebviewsModalIndexRouteImport } from './routes/webviews/modal/index'
import { Route as WebviewsPanelIdRouteImport } from './routes/webviews/panel/$id'

const rootIndexRoute = rootIndexRouteImport.update({
  id: '/(root)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const rootTooltipRoute = rootTooltipRouteImport.update({
  id: '/(root)/tooltip',
  path: '/tooltip',
  getParentRoute: () => rootRouteImport,
} as any)
const rootToastRoute = rootToastRouteImport.update({
  id: '/(root)/toast',
  path: '/toast',
  getParentRoute: () => rootRouteImport,
} as any)
const rootPopoverRoute = rootPopoverRouteImport.update({
  id: '/(root)/popover',
  path: '/popover',
  getParentRoute: () => rootRouteImport,
} as any)
const rootPanelRoute = rootPanelRouteImport.update({
  id: '/(root)/panel',
  path: '/panel',
  getParentRoute: () => rootRouteImport,
} as any)
const rootModalRoute = rootModalRouteImport.update({
  id: '/(root)/modal',
  path: '/modal',
  getParentRoute: () => rootRouteImport,
} as any)
const rootMenuRoute = rootMenuRouteImport.update({
  id: '/(root)/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const rootAppleIntelligenceRoute = rootAppleIntelligenceRouteImport.update({
  id: '/(root)/apple-intelligence',
  path: '/apple-intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const WebviewsTrayIndexRoute = WebviewsTrayIndexRouteImport.update({
  id: '/webviews/tray/',
  path: '/webviews/tray/',
  getParentRoute: () => rootRouteImport,
} as any)
const WebviewsPopoverIndexRoute = WebviewsPopoverIndexRouteImport.update({
  id: '/webviews/popover/',
  path: '/webviews/popover/',
  getParentRoute: () => rootRouteImport,
} as any)
const WebviewsModalIndexRoute = WebviewsModalIndexRouteImport.update({
  id: '/webviews/modal/',
  path: '/webviews/modal/',
  getParentRoute: () => rootRouteImport,
} as any)
const WebviewsPanelIdRoute = WebviewsPanelIdRouteImport.update({
  id: '/webviews/panel/$id',
  path: '/webviews/panel/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/apple-intelligence': typeof rootAppleIntelligenceRoute
  '/menu': typeof rootMenuRoute
  '/modal': typeof rootModalRoute
  '/panel': typeof rootPanelRoute
  '/popover': typeof rootPopoverRoute
  '/toast': typeof rootToastRoute
  '/tooltip': typeof rootTooltipRoute
  '/': typeof rootIndexRoute
  '/webviews/panel/$id': typeof WebviewsPanelIdRoute
  '/webviews/modal': typeof WebviewsModalIndexRoute
  '/webviews/popover': typeof WebviewsPopoverIndexRoute
  '/webviews/tray': typeof WebviewsTrayIndexRoute
}
export interface FileRoutesByTo {
  '/apple-intelligence': typeof rootAppleIntelligenceRoute
  '/menu': typeof rootMenuRoute
  '/modal': typeof rootModalRoute
  '/panel': typeof rootPanelRoute
  '/popover': typeof rootPopoverRoute
  '/toast': typeof rootToastRoute
  '/tooltip': typeof rootTooltipRoute
  '/': typeof rootIndexRoute
  '/webviews/panel/$id': typeof WebviewsPanelIdRoute
  '/webviews/modal': typeof WebviewsModalIndexRoute
  '/webviews/popover': typeof WebviewsPopoverIndexRoute
  '/webviews/tray': typeof WebviewsTrayIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(root)/apple-intelligence': typeof rootAppleIntelligenceRoute
  '/(root)/menu': typeof rootMenuRoute
  '/(root)/modal': typeof rootModalRoute
  '/(root)/panel': typeof rootPanelRoute
  '/(root)/popover': typeof rootPopoverRoute
  '/(root)/toast': typeof rootToastRoute
  '/(root)/tooltip': typeof rootTooltipRoute
  '/(root)/': typeof rootIndexRoute
  '/webviews/panel/$id': typeof WebviewsPanelIdRoute
  '/webviews/modal/': typeof WebviewsModalIndexRoute
  '/webviews/popover/': typeof WebviewsPopoverIndexRoute
  '/webviews/tray/': typeof WebviewsTrayIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/apple-intelligence'
    | '/menu'
    | '/modal'
    | '/panel'
    | '/popover'
    | '/toast'
    | '/tooltip'
    | '/'
    | '/webviews/panel/$id'
    | '/webviews/modal'
    | '/webviews/popover'
    | '/webviews/tray'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/apple-intelligence'
    | '/menu'
    | '/modal'
    | '/panel'
    | '/popover'
    | '/toast'
    | '/tooltip'
    | '/'
    | '/webviews/panel/$id'
    | '/webviews/modal'
    | '/webviews/popover'
    | '/webviews/tray'
  id:
    | '__root__'
    | '/(root)/apple-intelligence'
    | '/(root)/menu'
    | '/(root)/modal'
    | '/(root)/panel'
    | '/(root)/popover'
    | '/(root)/toast'
    | '/(root)/tooltip'
    | '/(root)/'
    | '/webviews/panel/$id'
    | '/webviews/modal/'
    | '/webviews/popover/'
    | '/webviews/tray/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  rootAppleIntelligenceRoute: typeof rootAppleIntelligenceRoute
  rootMenuRoute: typeof rootMenuRoute
  rootModalRoute: typeof rootModalRoute
  rootPanelRoute: typeof rootPanelRoute
  rootPopoverRoute: typeof rootPopoverRoute
  rootToastRoute: typeof rootToastRoute
  rootTooltipRoute: typeof rootTooltipRoute
  rootIndexRoute: typeof rootIndexRoute
  WebviewsPanelIdRoute: typeof WebviewsPanelIdRoute
  WebviewsModalIndexRoute: typeof WebviewsModalIndexRoute
  WebviewsPopoverIndexRoute: typeof WebviewsPopoverIndexRoute
  WebviewsTrayIndexRoute: typeof WebviewsTrayIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(root)/': {
      id: '/(root)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof rootIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(root)/tooltip': {
      id: '/(root)/tooltip'
      path: '/tooltip'
      fullPath: '/tooltip'
      preLoaderRoute: typeof rootTooltipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(root)/toast': {
      id: '/(root)/toast'
      path: '/toast'
      fullPath: '/toast'
      preLoaderRoute: typeof rootToastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(root)/popover': {
      id: '/(root)/popover'
      path: '/popover'
      fullPath: '/popover'
      preLoaderRoute: typeof rootPopoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(root)/panel': {
      id: '/(root)/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof rootPanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(root)/modal': {
      id: '/(root)/modal'
      path: '/modal'
      fullPath: '/modal'
      preLoaderRoute: typeof rootModalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(root)/menu': {
      id: '/(root)/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof rootMenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(root)/apple-intelligence': {
      id: '/(root)/apple-intelligence'
      path: '/apple-intelligence'
      fullPath: '/apple-intelligence'
      preLoaderRoute: typeof rootAppleIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webviews/tray/': {
      id: '/webviews/tray/'
      path: '/webviews/tray'
      fullPath: '/webviews/tray'
      preLoaderRoute: typeof WebviewsTrayIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webviews/popover/': {
      id: '/webviews/popover/'
      path: '/webviews/popover'
      fullPath: '/webviews/popover'
      preLoaderRoute: typeof WebviewsPopoverIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webviews/modal/': {
      id: '/webviews/modal/'
      path: '/webviews/modal'
      fullPath: '/webviews/modal'
      preLoaderRoute: typeof WebviewsModalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webviews/panel/$id': {
      id: '/webviews/panel/$id'
      path: '/webviews/panel/$id'
      fullPath: '/webviews/panel/$id'
      preLoaderRoute: typeof WebviewsPanelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  rootAppleIntelligenceRoute: rootAppleIntelligenceRoute,
  rootMenuRoute: rootMenuRoute,
  rootModalRoute: rootModalRoute,
  rootPanelRoute: rootPanelRoute,
  rootPopoverRoute: rootPopoverRoute,
  rootToastRoute: rootToastRoute,
  rootTooltipRoute: rootTooltipRoute,
  rootIndexRoute: rootIndexRoute,
  WebviewsPanelIdRoute: WebviewsPanelIdRoute,
  WebviewsModalIndexRoute: WebviewsModalIndexRoute,
  WebviewsPopoverIndexRoute: WebviewsPopoverIndexRoute,
  WebviewsTrayIndexRoute: WebviewsTrayIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
